name: 'Semantic versioning action'
description: 'This action creates a new semantic version based on git tags and desired release type.'
author: 'Your name or organization here'
inputs:
  releaseType:
    required: true
    description: 'what kind of release to perform'
    default: 'release'
outputs:
  newVersion:
    description: "new version"
runs:
  using: 'node16'
  main: 'dist/index.js'
